# coding: utf-8
"""
Django settings for mysite2 project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&zpmk=@&vz!a(y0e$v#@sczt^pisebm@82mzyhyg&g@!vldf)o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
import socket
hostname = socket.gethostname()
if hostname != 'darlin.local':
    IS_LOCAL = False
    USER_SESSION_EXPIRE = 10 * 60
    DEBUG = False
else:
    IS_LOCAL = True
    USER_SESSION_EXPIRE = None
    DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

DEFAULT_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

LOCAL_APPS = (
    'app.article',
    'app.account',
    'app.comments',
    'app.link',
)

THIRD_APPS = (
    'rest_framework',
    'corsheaders',
    'django_markdown',
    'django_mysql',
)

INSTALLED_APPS = DEFAULT_APPS + LOCAL_APPS + THIRD_APPS

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
)

ROOT_URLCONF = 'mysite2.urls'

CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if IS_LOCAL:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'api',
            'USER': 'root',
            'PASSWORD': 'Shiwei122',
            'HOST': 'mysql.darlin.me',
            'CHARSET': 'utf8',
            'PORT': '80',
        }
    }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'PAGE_SIZE': 20
}

SESSION_COOKIE_DOMAIN = '.darlin.me'
CSRF_COOKIE_DOMAIN = '.darlin.me'

if IS_LOCAL:
    SESSION_COOKIE_DOMAIN = 'localhost'
    CSRF_COOKIE_DOMAIN = 'localhost'

# CORS_ORIGIN_WHITELIST = (
#     'local.darlin.me',
#     'darlin.me',
#     'www.darlin.me',
#     'spider.darlin.me',
#     'new.darlin.me',
#     'http.darlin.me',
# )
CORS_ORIGIN_REGEX_WHITELIST = ('^(https?://)?(\w+\.)?darlin\.me$', )

CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'x-csrftoken',
    'user-agent',
    'accept-encoding',
    'x-aestoken',
)

AUTH_USER_MODEL = 'account.Profile'

QINIU_ACCESS_KEY = 'RR8xxStViBpzNJ4pQjD1sBZH3JsWN-ou-LR1D_iT'
QINIU_SECRET_KEY = '9oxjA6WIOGBRqUYnyVgrGzp4kEWbTzQ-lcW9Ear7'
QINIU_BUCKET_DEFAULT = 'qiniu-darlin-me'
QINIU_MEDIA_SRC = 'media/'

ALIYUN_KEY_ID = 'LTAIU6zaxUBGeayM'
ALIYUN_KEY_SECRET = 'o44wa1CilHPldl8XHDS7ymxVzt3kxl'
ALIYUN_BUCKET_ENDPOIONTS = 'http://oss-cn-shanghai.aliyuncs.com'
ALIYUN_BUCKET = 'darlin-me'
ALIYUN_MEDIA_SRC = 'media/'

GITHUB_AUTHORIZE_URL = 'https://github.com/login/oauth/authorize'
GITHUB_CLIENT_ID = 'c3b1f0c02a459943fbef'
GITHUB_CLIENT_SECRET = '63000036a72e6ac9e9a4bd39674b4caa9f134aa4'
GITHUB_CALLBACK = 'http://darlin.me'

QQ_AUTHORIZE_URL = 'https://graph.qq.com/oauth2.0/authorize'
QQ_CLIENT_ID = 101322546
QQ_CLIENT_SECRET = 'fda5515f98e536c2a28cd7706236b57a'

API_URL = ''
