version: '2'
 services:
   db:
     image: mysql
   web:
     build: .
     command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:9999
     volumes:
       - .:/code
     ports:
       - "9999:9999"
     depends_on:
       - db
